// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_mackbike/test/instructions_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:flutter_mackbike/features/navigation/models/route_model.dart'
    as _i7;
import 'package:flutter_mackbike/features/navigation/models/search_result_model.dart'
    as _i3;
import 'package:flutter_mackbike/features/navigation/view_models/navigation_view_model.dart'
    as _i2;
import 'package:flutter_map/flutter_map.dart' as _i4;
import 'package:latlong2/latlong.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NavigationViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationViewModel extends _i1.Mock
    implements _i2.NavigationViewModel {
  MockNavigationViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NavigationState get navigationState =>
      (super.noSuchMethod(
            Invocation.getter(#navigationState),
            returnValue: _i2.NavigationState.idle,
          )
          as _i2.NavigationState);

  @override
  List<_i3.SearchResultModel> get originSearchResults =>
      (super.noSuchMethod(
            Invocation.getter(#originSearchResults),
            returnValue: <_i3.SearchResultModel>[],
          )
          as List<_i3.SearchResultModel>);

  @override
  List<_i3.SearchResultModel> get destinationSearchResults =>
      (super.noSuchMethod(
            Invocation.getter(#destinationSearchResults),
            returnValue: <_i3.SearchResultModel>[],
          )
          as List<_i3.SearchResultModel>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setMapController(_i4.MapController? controller) => super.noSuchMethod(
    Invocation.method(#setMapController, [controller]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> fetchCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentLocation, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchLocation(String? query, {required bool? isOrigin}) =>
      (super.noSuchMethod(
            Invocation.method(#searchLocation, [query], {#isOrigin: isOrigin}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearSearchResults({required bool? isOrigin}) => super.noSuchMethod(
    Invocation.method(#clearSearchResults, [], {#isOrigin: isOrigin}),
    returnValueForMissingStub: null,
  );

  @override
  void setCurrentLocation(_i6.LatLng? location) => super.noSuchMethod(
    Invocation.method(#setCurrentLocation, [location]),
    returnValueForMissingStub: null,
  );

  @override
  void setOrigin(_i6.LatLng? location) => super.noSuchMethod(
    Invocation.method(#setOrigin, [location]),
    returnValueForMissingStub: null,
  );

  @override
  void setDestination(_i6.LatLng? location) => super.noSuchMethod(
    Invocation.method(#setDestination, [location]),
    returnValueForMissingStub: null,
  );

  @override
  void cancelRoutePreview() => super.noSuchMethod(
    Invocation.method(#cancelRoutePreview, []),
    returnValueForMissingStub: null,
  );

  @override
  void forceState(_i2.NavigationState? state) => super.noSuchMethod(
    Invocation.method(#forceState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void forceRoute(_i7.RouteModel? route) => super.noSuchMethod(
    Invocation.method(#forceRoute, [route]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> startNavigation() =>
      (super.noSuchMethod(
            Invocation.method(#startNavigation, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void stopNavigation() => super.noSuchMethod(
    Invocation.method(#stopNavigation, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
