// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_mackbike/test/navigation_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_mackbike/features/navigation/models/route_model.dart'
    as _i2;
import 'package:flutter_mackbike/features/navigation/models/search_result_model.dart'
    as _i7;
import 'package:flutter_mackbike/features/navigation/services/geocoding_service.dart'
    as _i6;
import 'package:flutter_mackbike/features/navigation/services/location_service.dart'
    as _i3;
import 'package:flutter_mackbike/features/navigation/services/routing_service.dart'
    as _i8;
import 'package:geolocator/geolocator.dart' as _i5;
import 'package:latlong2/latlong.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRouteModel_0 extends _i1.SmartFake implements _i2.RouteModel {
  _FakeRouteModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i3.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i4.Future<_i5.LocationPermission>.value(
              _i5.LocationPermission.denied,
            ),
          )
          as _i4.Future<_i5.LocationPermission>);

  @override
  _i4.Future<_i5.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i4.Future<_i5.LocationPermission>.value(
              _i5.LocationPermission.denied,
            ),
          )
          as _i4.Future<_i5.LocationPermission>);

  @override
  _i4.Future<_i5.Position?> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i4.Future<_i5.Position?>.value(),
          )
          as _i4.Future<_i5.Position?>);

  @override
  _i4.Stream<_i5.Position> getPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, []),
            returnValue: _i4.Stream<_i5.Position>.empty(),
          )
          as _i4.Stream<_i5.Position>);

  @override
  void stopPositionStream() => super.noSuchMethod(
    Invocation.method(#stopPositionStream, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GeocodingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeocodingService extends _i1.Mock implements _i6.GeocodingService {
  MockGeocodingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.SearchResultModel>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i4.Future<List<_i7.SearchResultModel>>.value(
              <_i7.SearchResultModel>[],
            ),
          )
          as _i4.Future<List<_i7.SearchResultModel>>);
}

/// A class which mocks [RoutingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutingService extends _i1.Mock implements _i8.RoutingService {
  MockRoutingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RouteModel> getRoute(
    _i9.LatLng? origin,
    _i9.LatLng? destination,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoute, [origin, destination]),
            returnValue: _i4.Future<_i2.RouteModel>.value(
              _FakeRouteModel_0(
                this,
                Invocation.method(#getRoute, [origin, destination]),
              ),
            ),
          )
          as _i4.Future<_i2.RouteModel>);
}
